### ISSUE TITLE
y_test causing non-reproducible

### ISSUE THREAD

**Issue by yilisg** [andland/libFMexe#13]
Since y_test is for the test set, the actual target might not be known in advance and hence I would not expect libFM to use y_test in anyway. That said, running the following snippet has resulted in different outcome on my system. Could it be a bug or is this intended behavior (based on some random seed that I missed)? Thanks.

```
data(movie_lens)

set.seed(1)
train_rows = sample.int(nrow(movie_lens), nrow(movie_lens) * 2 / 3)
train = movie_lens[train_rows, ]
test  = movie_lens[-train_rows, ]

#- Save the original test ratings
actual_rating <- test$Rating

predFM1 = libFM(train, test, Rating ~ User + Movie, task = "r", dim = 10, iter = 500)
mean((predFM1 - actual_rating)^2) # 0.8186519

#- Set test$Rating to 0
test$Rating <- 0L

predFM2 = libFM(train, test, Rating ~ User + Movie, task = "r", dim = 10, iter = 500)
mean((predFM2 - actual_rating)^2) # 0.8177446

#- Set test$Rating to 99
test$Rating <- 99L

predFM3 = libFM(train, test, Rating ~ User + Movie, task = "r", dim = 10, iter = 500)
mean((predFM3 - actual_rating)^2) # 0.8186338

sum(abs(predFM1 - predFM2)) # 1618.705
sum(abs(predFM1 - predFM3)) # 1470.594
sum(abs(predFM2 - predFM3)) # 1598.060
```

**Comment by andland** [comment]
You are correct that the test rating should not need to be present because you often will not know it. libFM's API however requires that you have a response variable, even for test data. In the executable, it is used to print out how well the algorithm is fitting a validation dataset. In my R package, when the response is not precent, I just use 0's (I think).

The reason you are getting different results is just due to different random seeds. I don't think I built in a way to pass a random seed to the libFM algorithm. I think the mcmc algorithm is the only one that has the random component, so other specifications should produce the same result.

I reran your code and looked at the correlations. They were all greater than 0.995, so these predictions are pretty close. In fact, I averaged them together and got even lower MSE.

```
cor(cbind(predFM1, predFM2, predFM3))
```

**Comment by yilisg** [comment]
Thanks Andrew. I was working on a different and much larger dataset, and this randomness seemed to be causing problem due to the large variations (with correlations between the predictions of different runs less than 0.7). I've uploaded a sub-sample of the data (only 10k rows) -- and the code snippet which I did 3 runs produced AUCs between 0.68 to 0.74 (and accuracy between 63% to 70%). Is there any workaround this? I tried changing method to "sgd" but got an error message.

Appreciate your thoughts and time looking into this.

[https://dl.dropboxusercontent.com/u/1272401/fmTrainValidateSubsample.RData]

```
library(libFMexe)

load("fmTrainValidateSubsample.RData")

fmValidateModel_Run1 = libFM(as.matrix(fmTrainX), as.matrix(fmValidateX), fmTrainY, fmValidateY, method = "mcmc", task = "c", dim = 10, iter = 500, verbosity=1)
print(paste0("AUC: ", round(AUC:::auc(AUC:::roc(fmValidateModel_Run1, factor(fmValidateY))), 6))) # AUC: 0.682989
print(mean(round(fmValidateModel_Run1) == fmValidateY)) # Accuracy: 0.6395

fmValidateModel_Run2 = libFM(as.matrix(fmTrainX), as.matrix(fmValidateX), fmTrainY, fmValidateY, method = "mcmc", task = "c", dim = 10, iter = 500, verbosity=1)
print(paste0("AUC: ", round(AUC:::auc(AUC:::roc(fmValidateModel_Run2, factor(fmValidateY))), 6))) # AUC: 0.721594
print(mean(round(fmValidateModel_Run2) == fmValidateY)) # Accuracy: 0.6810

fmValidateModel_Run3 = libFM(as.matrix(fmTrainX), as.matrix(fmValidateX), fmTrainY, fmValidateY * 0L, method = "mcmc", task = "c", dim = 10, iter = 500, verbosity=1)
print(paste0("AUC: ", round(AUC:::auc(AUC:::roc(fmValidateModel_Run3, factor(fmValidateY))), 6))) # AUC: 0.74622
print(mean(round(fmValidateModel_Run3) == fmValidateY)) # Accuracy: 0.7072

fmValidateModel_Run4 = libFM(as.matrix(fmTrainX), as.matrix(fmValidateX), fmTrainY, fmValidateY * 0L, method = "sgd", task = "c", dim = 10, iter = 500, verbosity=1)

# Error in libFM.default(train, test, validation = validation, grouping = grouping,  : 
#                         could not find function "is.missing"
```

**Comment by andland** [comment]
The reason the sgd option gave an error is because of a bug in the code. I have fixed it. Reinstalling with `devtools::install_github("andland/libFMexe")` will fix the issue. Although sgd requires adjusting the tuning parameters, and the defaults for this application are very poor, so they will not give you a good result.

For the mcmc code, I ran the same code as you and get similar variability. The only thing I can suggest is for you to run it for many more iterations. Maybe 5000 or more. I did so and got AUCs of 0.83, 0.75 and 0.83 and accuracies of 0.71, 0.68, and 0.73, respectively. Averaging the three predictions together gave me an AUC of 0.84 and accuracy of 0.74.

If I had to guess, one reason for the variability may be due to the use of continuous variables. In general, I use libFM with binary/categorical variables and do not have much experience with the performance with continuous. In particular, `n_unique_people` has a very large range, so small changes in the parameters will cause large changes in the outputs. I'm not sure if libFM does any scaling internally. An option is to turn continuous variables categorical with something like `cut`.

**Comment by yilisg** [comment]
Thanks Andrew. Discretizing/binning continuous variables indeed helped to reduced the variance of the predictions. Also appreciate the fix.

**Comment by andland** [comment]
I just realized that the [development version](https://github.com/srendle/libfm) of libFM has a seed option. If you built the executable from source, then you should have it as well. I added the `seed` option to this package in the latest commit. E.g.

```
fmValidateModel_Run1 = libFM(as.matrix(fmTrainX), as.matrix(fmValidateX), fmTrainY, fmValidateY, method = "mcmc", task = "c", dim = 10, iter = 500, verbosity=1, seed = 99)
```

**Comment by yilisg** [comment]
Great! Thanks Andrew.
